taxonomy.vocabulary.*.third_party.rdf_entity:
  type: mapping
  label: 'Third party settings'
  mapping:
    graph:
      type: sequence
      sequence:
        type: string
        label: 'The mapping of a graph definition to a graph uri.'
    mapping:
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: string
          label: 'Mapping of field properies to their rdf counterpart.'
